name: gradle-ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Fetch iris
      uses: actions/checkout@v2
      with:
        repository: 'HyperCubeMC/Iris'
        ref: '1.18-starline'
        path: 'iris'
    - name: Iris publishToMavenLocal
      run: cd ./iris && ./gradlew publishToMavenLocal && cd ..
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs
    - name: Clean remove old jars
      run: rm ./build/*.jar || true
    - name: Rename files
      run: |
        cd build/libs
        mv *sources-dev.jar ../sodium-fabric-starline-sources-dev.jar
        mv *sources.jar ../sodium-fabric-starline-sources.jar
        mv *dev.jar ../sodium-fabric-starline-dev.jar
        mv *.jar ../sodium-fabric-starline.jar
        rm -r ../libs || true
    - name: Save jars to repo
      run: |
        cd build
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add ./*.jar -f || true
        git commit -m "Update jars"
        git push 
